"""
Core domain data models and immutable schema entities for Google Form automation.
Enforces strict typing and self-documenting data representation across domain boundaries.
"""
import uuid
from datetime import datetime
from enum import Enum
from typing import List, Optional, Union, Dict, Any
from pydantic import BaseModel, Field


class QuestionType(str, Enum):
    """Supported form interaction control types across target web forms."""
    SHORT_ANSWER = "short_answer"
    PARAGRAPH = "paragraph"
    MULTIPLE_CHOICE = "multiple_choice"
    CHECKBOXES = "checkboxes"
    DROPDOWN = "dropdown"
    LINEAR_SCALE = "linear_scale"
    DATE = "date"
    TIME = "time"
    UNKNOWN = "unknown"


class Question(BaseModel):
    """Represents an individual interactive field extracted from a target form."""
    id: str = Field(description="Unique internal identifier or DOM index for the question element.")
    title: str = Field(description="The question prompt text displayed to the respondent.")
    description: Optional[str] = Field(None, description="Optional supporting instructions beneath the prompt.")
    question_type: QuestionType = Field(default=QuestionType.UNKNOWN, description="Interactive control type.")
    required: bool = Field(default=False, description="True if an answer is required to proceed or submit.")
    options: List[str] = Field(default_factory=list, description="Choice labels for radio, checkbox, or dropdown fields.")
    
    # Linear scale metadata
    scale_min: Optional[int] = Field(None, description="Minimum numerical rating boundary (e.g., 1).")
    scale_max: Optional[int] = Field(None, description="Maximum numerical rating boundary (e.g., 5 or 10).")
    scale_label_min: Optional[str] = Field(None, description="Anchor label for minimum score (e.g., 'Poor').")
    scale_label_max: Optional[str] = Field(None, description="Anchor label for maximum score (e.g., 'Excellent').")


class FormPage(BaseModel):
    """Represents a sequential section or page within a multi-page form."""
    page_number: int = 1
    questions: List[Question] = Field(default_factory=list)
    has_next_page: bool = Field(default=False, description="True if subsequent sections follow this page.")


class FormSchema(BaseModel):
    """Comprehensive structural blueprint of a target form across all discovered pages."""
    url: str
    title: str = Field("Untitled Form", description="Primary headline of the target form.")
    description: Optional[str] = Field(None, description="General instructions or preface at the top of the form.")
    pages: List[FormPage] = Field(default_factory=list)
    
    @property
    def all_questions(self) -> List[Question]:
        """Returns a flattened list of all questions discovered across all form pages."""
        questions: List[Question] = []
        for page in self.pages:
            questions.extend(page.questions)
        return questions


class Persona(BaseModel):
    """Synthetic human demographic identity governing response consistency and tone."""
    name: str = Field(description="Full synthetic respondent name.")
    age: int = Field(description="Respondent age in years.")
    occupation: str = Field(description="Professional job role or academic affiliation.")
    background: str = Field(description="Narrative context detailing lifestyle and domain proficiency.")
    sentiment: str = Field(description="Qualitative sentiment description towards the survey subject matter.")
    traits: List[str] = Field(default_factory=list, description="Key behavior traits influencing qualitative narrative replies.")
    latent_score: float = Field(0.0, description="Continuous psychological sentiment score (-1.0 to 1.0) governing conditional correlation.")


class AnswerItem(BaseModel):
    """An individual generated response mapped to a specific form question."""
    question_id: str = Field(description="Matches Question.id in the corresponding FormSchema.")
    question_title: str = Field(description="The verbatim prompt of the question being answered.")
    value: Union[str, List[str], int] = Field(
        description="The chosen response: string for radio/dropdown/text, list of strings for checkboxes, or int for scales."
    )


class FormAnswerSet(BaseModel):
    """Comprehensive set of responses generated by a Persona for a complete form submission attempt."""
    persona: Persona
    answers: List[AnswerItem] = Field(default_factory=list)

    def get_answer(self, question_id: str) -> Optional[AnswerItem]:
        """Retrieves a generated response matching the specified question ID."""
        for ans in self.answers:
            if ans.question_id == question_id:
                return ans
        return None


class SubmissionRecord(BaseModel):
    """Audit ledger entry logging historical submission attempts and response data."""
    timestamp: str = Field(default_factory=lambda: datetime.now().isoformat())
    form_url: str
    persona: Persona
    answers: List[AnswerItem]
    success: bool
    error_message: Optional[str] = None


class ScheduleStatus(str, Enum):
    """Lifecycle tracking states for asynchronous scheduled survey submission tasks."""
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class ScheduledSubmissionTask(BaseModel):
    """Encapsulates a persistent queued task for submitting a FormAnswerSet at a pre-decided timestamp."""
    task_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    form_url: str
    scheduled_timestamp: str = Field(description="ISO-8601 formatted target execution timestamp")
    answer_set_json: str = Field(description="Serialized JSON representation of FormAnswerSet")
    status: ScheduleStatus = Field(default=ScheduleStatus.PENDING)
    attempts: int = Field(default=0)
    last_error: Optional[str] = None
    created_at: str = Field(default_factory=lambda: datetime.now().isoformat())
    completed_at: Optional[str] = None


class PsychometricProfile(BaseModel):
    """Multi-dimensional trait vectors for Gaussian Copula behavioral correlation."""
    persona_id: str
    tech_enthusiasm: float = Field(default=0.0, description="Normalized Z-score (-3 to +3) for technical adoption & optimism.")
    risk_skepticism: float = Field(default=0.0, description="Normalized Z-score (-3 to +3) for privacy, security & license caution.")
    pragmatic_workflow: float = Field(default=0.0, description="Normalized Z-score (-3 to +3) for practical utility vs hype.")
    trait_weights: Dict[str, float] = Field(default_factory=dict, description="Custom domain-specific trait Z-scores.")

